STATUS_PENDING = "Pending"
STATUS_AUTO_APPROVED = "Auto Approved"
STATUS_MANUAL_APPROVED = "Manually Approved"
AUTO_APPROVAL_THRESHOLD = 3
EMAIL_AUTO_SENT = "Auto Sent"
EMAIL_PENDING_APPROVAL = "Pending Approval"
EMAIL_IN_QUEUE = "In Queue"